### ISSUE TITLE
add country to "location" column

### ISSUE THREAD

**Issue by menschikov** [windingtree/orgid-explorer#36]
It's not clear where's the company located, we need to add country to that field so the template will be something like "Praha, CZ" or "Prague, Czech Republic"

**Comment by menschikov** [comment]
![image](https://user-images.githubusercontent.com/4557491/69005708-cc1cf800-0947-11ea-807a-939126faa209.png)

**Comment by MatiasOS** [comment]
Backed is only returning the city. To solve this issue we need to consume a service to fetch and complete all the corresponding country for each city. Probably is better to resolve this in backend during caching process.
